name: Publish on Master

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v1
        if: github.event.pull_request.merged
        with:
          fetch-depth: 1
      - name: Get yarn cache
        if: github.event.pull_request.merged
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        if: github.event.pull_request.merged
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/setup-node@v1
        if: github.event.pull_request.merged
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install
        if: github.event.pull_request.merged
        run: yarn
      - name: Build
        if: github.event.pull_request.merged
        run: yarn build --base-href=/kikstart-ui/
      - name: Release
        if: github.event.pull_request.merged
        run: yarn semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
      - name: Deploy to GitHub Pages
        if: github.event.pull_request.merged
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.GH_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist/kikstart-ui
      - name: Deploy to GitHub Pages
        if: github.event.pull_request.merged
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist/kikstart-ui
